//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.HttpApi.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.HttpApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AuthIP 的本地化字符串。
        /// </summary>
        internal static string AuthIP {
            get {
                return ResourceManager.GetString("AuthIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthLogin 的本地化字符串。
        /// </summary>
        internal static string AuthLogin {
            get {
                return ResourceManager.GetString("AuthLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthRole 的本地化字符串。
        /// </summary>
        internal static string AuthRole {
            get {
                return ResourceManager.GetString("AuthRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthToken 的本地化字符串。
        /// </summary>
        internal static string AuthToken {
            get {
                return ResourceManager.GetString("AuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthTraffic 的本地化字符串。
        /// </summary>
        internal static string AuthTraffic {
            get {
                return ResourceManager.GetString("AuthTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthUser 的本地化字符串。
        /// </summary>
        internal static string AuthUser {
            get {
                return ResourceManager.GetString("AuthUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthVerbs 的本地化字符串。
        /// </summary>
        internal static string AuthVerbs {
            get {
                return ResourceManager.GetString("AuthVerbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CacheSeconds 的本地化字符串。
        /// </summary>
        internal static string CacheSeconds {
            get {
                return ResourceManager.GetString("CacheSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DefaultValue 的本地化字符串。
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExpireDate 的本地化字符串。
        /// </summary>
        internal static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string ParamName {
            get {
                return ResourceManager.GetString("ParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string ParamValue {
            get {
                return ResourceManager.GetString("ParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PostFile 的本地化字符串。
        /// </summary>
        internal static string PostFile {
            get {
                return ResourceManager.GetString("PostFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReturnType 的本地化字符串。
        /// </summary>
        internal static string ReturnType {
            get {
                return ResourceManager.GetString("ReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url 的本地化字符串。
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
